name             'apache_test'
maintainer       'Mike Splain'
maintainer_email 'mike.splain@gmail.com'
license          'All rights reserved'
description      'Installs/Configures apache_test'
long_description 'Installs/Configures apache_test'
version          '0.1.0'

depends 'apache2'
depends 'apt'
depends 'yum'
