---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  nodes_path: test/fixtures/nodes

platforms:
  - name: ubuntu-12.04
  # - name: centos-6.4

suites:
  - name: server1
    run_list:
    - recipe[consul_test::server]
    driver:
      network:
      - ["private_network", {ip: "192.168.33.33"}]
    attributes:
      consul:
        bind_addr: 192.168.33.33
  - name: server2
    run_list:
    - recipe[consul_test::server]
    driver:
      network:
      - ["private_network", {ip: "192.168.33.34"}]
    attributes:
      consul:
        bind_addr: 192.168.33.34
  - name: server3
    run_list:
    - recipe[consul_test::server]
    driver:
      network:
      - ["private_network", {ip: "192.168.33.35"}]
    attributes:
      consul:
        bind_addr: 192.168.33.35
  - name: client1
    run_list:
    - recipe[consul_test::client]
    driver:
      network:
      - ["private_network", {ip: "192.168.33.36"}]
    attributes:
      consul:
        bind_addr: 192.168.33.36
